# 지킬에 온 걸 환영해!
#
# 이 구성 파일은 전체 블로그, 값에 영향을 미치는 설정을 위한 것입니다.
# 한 번 설정하고 그 이후에는 거의 편집할 수 없습니다. 찾으면
# 이 파일을 매우 자주 편집하는 본인, 지킬의 데이터 파일을 사용하는 것을 고려하십시오.
# 자주 업데이트해야 하는 데이터에 대한 기능.
#
# 기술적인 이유로 이 파일은 *NOT*를 사용할 때 자동으로 다시 로드됩니다.
# 'exec exec jekyl serve'. 이 파일을 변경하면 서버 프로세스를 다시 시작하십시오.
#
# YAML 구문에 대한 도움말이 필요한 경우 몇 가지 빠른 참조가 있습니다.
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#httpsl
# https://learnxinyminutes.com/docs/yaml/
#
# 사이트 설정
# 새 사이트를 개인 설정하는 데 사용됩니다. HTML 파일을 보면,
# {{site.filename}}, {{site.email}}} 등을 통해 액세스할 수 있습니다.
# 원하는 모든 사용자 지정 변수를 만들 수 있으며, 이러한 변수는 액세스할 수 있습니다.
# {{site.myvariable}}을(를) 통해 템플릿에 표시됩니다.

title: KimTank repository
tagline: 으쌰으쌰
lang: ko_KR
author.name: KimTank
author.url: https://kimtank.github.io/

markdown: kramdown
repository: kimtank/kimtank.github.io
# tags_path: A path to the archive-by-tags page, It is used by tags on each post
# categories_path: A path to the archive-by-categories page; It is used by categories on each post

disqus: unDo

email: sycor123k@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  at the long time ago..
baseurl: kimtank # the subpath of your site, e.g. /blog
url: https://kimtank.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kimtank86
github_username:  kimtank
#추가
# facebook_username: sycork
# instagram_username: sycork

# Build settings
#----------- 기존 테마 theme: minima
#----------- 테마 추가
theme: monophase
#----------- 기존 플러그인에 추가
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: zivhub/monophase@main

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
